### ISSUE TITLE
Proposing develop branch and styling question

### ISSUE THREAD

**Issue by mbeacom** [sassoftware/python-swat#1]
Hello @kesmit13!

First off, thank you for the repository!

Would it be possible for you to publish a `develop`/`development` branch to maintain separation between stable and development source states?

Additionally, do you have a preference on docstring documentation and commenting? PEP-257 and PEP-258?  Are you open to using [NumPy](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt) or [Google python](https://google.github.io/styleguide/pyguide.html#Comments) style docstrings for method, class, and module documenting?

Thank you!

**Comment by kesmit13** [comment]
At the moment, we are trying to keep the development environment as simple as possible.  We had considered adding a persistent development branch, but decided not to until we absolutely need to.  However, that doesn't prevent you from forking the repository and developing things on your own.  We expect the master branch to be stable at all times, so pull requests must be accompanied by test cases in order to be accepted.

As far as documentation goes, we use NumPy docstrings in all of our code, with a couple of minor changes that don't affect their processing.  We tend to use triple-single-quotes rather than double-quotes simply because it looks cleaner.  You can browse the source to see the doctoring style.
