### ISSUE TITLE
Maintaining SASDataFrame datetime64[ns] format after importing to CAS with upload_frame()

### ISSUE THREAD

**Issue by timtan-github** [sassoftware/python-swat#111]
How do I maintain the datetime format when using upload_frame()? In CAS, the dates becomes varchar format. 

I tried: 
conn.upload_frame(df, importoptions= dict(filetype="CSV", encoding='utf-8', vars=[dict(name="date_published_dt",informat="ANYDTDTE9.")]), casout = dict(name="df", caslib="public", promote='True'))

ERROR: The destination buffer size was not sufficient for the transcoded data.

**Comment by kesmit13** [comment]
`upload_frame` exports the dataframe to a CSV file then uploads it. This works with both the binary and HTTP interfaces of CAS. If you are using the binary protocol (typically port 5570), you can enable a different form of upload that will attempt to preserve all data types. You can also use the `read_frame` method with the `use_addtable=True` parameter. This will use the `table.addtable` action rather than `table.upload`. I will mention that not all CAS actions support the extended data types though.
```
tbl = conn.read_frame(df, casout = dict(name="df", caslib="public", promote='True'))
```

**Comment by timtan-github** [comment]
Ah okay. Thanks! I'm connected via windows on 8777 so this wouldn't work for me but its a good to know. I ended up running conn.dataStep.runCode to convert the varchar dates back to date format as a workaround after using upload_frame. Thanks for the quick response.

**Comment by gygabyte017** [comment]
> 
> 
> `upload_frame` exports the dataframe to a CSV file then uploads it. This works with both the binary and HTTP interfaces of CAS. If you are using the binary protocol (typically port 5570), you can enable a different form of upload that will attempt to preserve all data types. You can also use the `read_frame` method with the `use_addtable=True` parameter. This will use the `table.addtable` action rather than `table.upload`. I will mention that not all CAS actions support the extended data types though.
> 
> ```
> tbl = conn.read_frame(df, casout = dict(name="df", caslib="public", promote='True'))
> ```

@kesmit13 didn't know about `read_frame` very interesting method, it is undocumented though right? I can't find it in the official docs.

**Comment by kesmit13** [comment]
@gygabyte017 I think this might just be a mistaken omission in the docs. It is a public method so, it's ok to use it.

**Comment by kesmit13** [comment]
I just added a `date_format` parameter to the `upload` method which can help solve your problem (7eeac93332c5ed50c12004f1cc1f8fcb06f7b898). This allows you to specify the exact date / time / datetime format to use for datetimes in your DataFrame. By default, this will still only upload as varchar using that format, however, you can use `importoptions` to specify the data type, format, and informat to use for that column. You just need to make sure that your `date_format` and informat agree. Since this technique uses the `table.upload` CAS action, it will work with both binary and REST.
