### ISSUE TITLE
Execute SAS Code using SWAT

### ISSUE THREAD

**Issue by seanankenbruck** [sassoftware/python-swat#12]
Hello,

I would like to execute a SAS program, or SAS programming statement, from a Python instance in a Viya environment. However, to this point I have not been able to find a way to execute a SAS program from Python using swat. Is there a viable way to do this? 

Specifically, I am looking for the equivalent operation to the magic commands that exist in SASpy2.1.6. The example in the SASpy documentation uses the following syntax to execute a SAS statement: 

```
%%SAS
proc print data=sashelp.class;
run;

data work.a;
  set sashelp.cars;
run;
```

Are these commands, or some other similar command, available in swat? Ideally, I would like to execute an entire SAS program from within my Python environment without having to re-write it using the action set syntax mentioned in the documentation.

**Comment by kesmit13** [comment]
This is not possible.  The CAS server that SWAT connects to does not support general SAS code.  It can only run actions.  SASpy can submit SAS code because it has a running version of the SAS System behind it, but CAS does not have that ability.  

There are some CAS-enabled procs that can process data if it is already in a CAS table.  Then you can use SASpy to invoke the code for those procs.  That is still outside of the scope of SWAT though.

**Comment by seanankenbruck** [comment]
Can you execute the concept of a SAS Job, meaning that if you have a sas program stored in your SAS environment and you would like to trigger its execution remotely, can that be accomplished through some sort of REST call or API?

**Comment by kesmit13** [comment]
Not in the CAS server.  It doesn't have a SAS language processor, macros, etc.  It just executes actions.  While you can submit them using REST, you are submitting action calls, not SAS code.  The one bit of SAS code that you can submit in CAS is data step.  There is a datastep.runcode action that will run data step code the same as in SAS.
