### ISSUE TITLE
Creating new columns

### ISSUE THREAD

**Issue by Mespith** [sassoftware/python-swat#22]
Hi! First of all, I think the SWAT package is very cool and I really want to help contribute, so I will look into that. In the meantime I would like to start a discussion on how one could add a new column to a CASTable. The pandas syntax does not seem to work.
`df['new column'] = list_of_values`
This does not give an error on its own, but when you continue to work with the CASTable it will raise the following error:
![image](https://user-images.githubusercontent.com/7500718/43001411-6f83972a-8c25-11e8-818d-a85056f75d9e.png)

A constant value does not seem to give a problem, but anything else seems to break the CASTable. Any thoughts on how we could implement this kind of syntax?

**Comment by kesmit13** [comment]
At the moment, CAS doesn't allow adding new columns to a table without rewriting the whole table.  The exception is using computed columns which can be created with a single value or an expression containing other columns in the same table.  For example:

```
df['new_column'] = df['col1'] + 2
df['new_column'] = 10
df['new_column'] = df['col1'] * df['col2']
```

But attempting to create a new column where the values of each row are specified in a list will not work.  The main reason is that CAS tables are not mutable without rewriting the whole table, but even if you could rewrite the whole table, row indexes are not deterministic, so there would be no way to know which value corresponds to which row.

The code you are attempting in your example probably should be raising an error in the Python side and even attempting to do the operation.

**Comment by kesmit13** [comment]
You can use data step in CAS to step through a data set much like you do in SAS, but it will typically do it in a distributed way so that the operations can be done in parallel on multiple machines.  Because of that, the stepping through the data doesn't happen in any specified order (unless you specify a BY statement).  That means that you can add a new column, but it's really up to the user to decide how to determine which row the data point goes into (usually by checking a key column, or just computing values based on existing values).

As far as your code above, it doesn't generate an error about the value now, but that is something that should be added to the SWAT package.  At the moment, it looks for special types such as CASColumn objects, but doesn't verify that it is a scalar that can be used by data step.

**Comment by kesmit13** [comment]
I've pushed a change (24d05868169a790e40c6443e5346cfa9784506ac) that should prevent attempts to set values to a column that aren't currently supported.
