### ISSUE TITLE
upload_frame cannot handle line breaks and quotes

### ISSUE THREAD

**Issue by Mespith** [sassoftware/python-swat#25]
Me and a colleague of mine have encountered the same problem while trying to upload a pandas DataFrame with text in one of the columns. When trying to upload the dataframe the following error occurs:

> ERROR: At least one row of input data is invalid: too few columns.
ERROR: At least one row of input data is invalid: too few columns.
ERROR: The action stopped due to errors.

This can be caused by either line breaks or a mixture of double and single quotes. This error is kind of confusing because pandas is not sensitive to these issues. It is caused by the fact that in the background the dataframe is stored as a csv and then uploaded to CAS. It is CAS that does not handle the text very well. This took me some time to figure out and my colleague actually couldn't and came to me for help.

I have made a very simple fix for this. It's a function that replaces line breaks by spaces and forces double quates to be single quotes. 
![image](https://user-images.githubusercontent.com/7500718/46463853-3666ed80-c7c5-11e8-813e-258646f2f925.png)
And you use it by applying it to the text column:
`df["new_text"] = df.text.apply(add_brackets)`

I was wondering if this could somehow be implemented into swat. Since this is a possible issue for every character variable uploaded to CAS, this method could be applied to any non-numeric column, right?

Let me know what you think and if I could help somehow.

**Comment by kesmit13** [comment]
After talking to some people in the CAS team, the newline issue is rather tricky since CSV files are not necessarily parsed in a linear manner from top-to-bottom.  Replacing newlines with another character may be the only way to fix this issue (at least for now, they are working on alternative means to handle this).  Modifying the DataFrame that's given to us to upload probably isn't the best approach, since we'd be modifying their data.  However, I don't see an option in the pandas to_csv method to change the character, so it might take more research.

As far as quotes go, those should be escaped using an extra double quote like this "aaa", "b""bb", "ccc".  I'd have to look at what pandas is doing in to_csv to see what's happening there. 

Of course, if you have any more ideas or patches, I'd be more than happy to take a look at them.

**Comment by onnoowl** [comment]
It looks like pandas' to_csv does support changing the character via the line_terminator option.
e.g. `data.to_csv(filename, encoding='utf-8', index=False, line_terminator="\r\n")`

Perhaps \r\n might be a reasonable choice in order to avoid this error. According to some folks on the CAS team, CAS doesn't support using \r\n as a line break in text data, but it does support \r\n as a CSV line delimiter, which means using it would avoid conflicts.

However, maybe a better solution would be to more heavily promote the use of read_frame(use_addtable=True), since this avoids the CSV transformation altogether. It seems like it should be favored anyway simply because of its performance improvements, but I noticed that it's not mentioned in the official documentation.

It looks like functions that support use_addtable also always check to see if the REST protocol is being used via `self._protocol.startswith('http')`. Given this, how come use_addtable always defaults to False? Wouldn't it be safe to always default to True? If so, is it worth breaking backwards compatibility in favor of ergonomics and performance by changing the default to true (especially since use_addtable doesn't show up in the documentation as far as I can tell)?

**Comment by kesmit13** [comment]
The addtable mode was the default in earlier versions of SWAT, but consistency between the protocols was deemed more important.  There are other differences when you use addtable as well (primarily, it will use the full set of CAS data types such as int32, int64, etc. rather than just doubles).  This caused other differences between the binary and REST protocols.  In the latest versions of the CAS server, you can specify those data types in the CSV parser so it could be more compatible, but the SWAT client hasn't been updated for that yet.

**Comment by onnoowl** [comment]
What about changing the default CSV line delimiter when uploading a data frame to \r\n as a short term solution then?

**Comment by kesmit13** [comment]
Fixed in f9710d341ff704ff0133b0f904cc893a8b0bec4b
