### ISSUE TITLE
Connection Time out Error

### ISSUE THREAD

**Issue by veerendra-pappoppula** [sassoftware/python-swat#48]
after installing the swat module, I tried this:

conn = swat.CAS('sasvad01.wcuds.net', 5570, '75vpappoppul', 'pwd')

and it timed out.

ERROR: The TCP/IP tcpSockConnect support routine failed with error 10060 (The connection has timed out.).
ERROR: Failed to connect to host 'sasvad01.wcuds.net', port 5570.
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\swat\cas\connection.py", line 303, in __init__
    self._sw_connection = clib.SW_CASConnection(*params)
  File "C:\Python\lib\site-packages\swat\clib.py", line 94, in SW_CASConnection
    return _pyswat.SW_CASConnection(*args, **kwargs)
SystemError: <class 'py37swat.SW_CASConnection'> returned NULL without setting an error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    conn = swat.CAS('sasvad01.wcuds.net', 5570, '75vpappoppul', 'Zxcv1234')
  File "C:\Python\lib\site-packages\swat\cas\connection.py", line 310, in __init__
    raise SWATError(self._sw_error.getLastErrorMessage())
swat.exceptions.SWATError: Could not connect to 'sasvad01.wcuds.net' on port 5570.

Am I doing something wrong? The CAS server is a remote linux machine.

**Comment by kesmit13** [comment]
The only thing I can think is that you have some sort of firewall between your client and the CAS server that is preventing a connection from being made and it's timing out.

**Comment by veerendra-pappoppula** [comment]
I might be wrong when i say this, but I can connect to the server directly
using tools winscp, mobaxterm. If there is a firewall issue, then the
server should not let me login using those applications right?

**Comment by kesmit13** [comment]
Not necessarily.  It could be that the firewall allows scp ports to pass through, but not 5570.  You could try connecting with another tool like curl and see what sort of message it gives.  It will be an error, but might give some additional info.
```
curl http://sasvad01.wcuds.net:5570
```

**Comment by nadolsw** [comment]
I am also having a similar issue with being unable to connect to CAS via SWAT due to timeouts. However, I am attempting to connect from within the SAS Analytic Cloud Service (SAC): https://www.sas.com/en_us/software/machine-learning-cloud.html

SAC offers both SAS Studio and JupyterLab applications. Specifically, I am attempting to connect to CAS via SWAT from within the JupyterLab application using the following command but not having any luck. Unfortunately, I am unable to track down the server host name and port information from within the instance so I've defaulted to trying with the login URL.

conn = swat.CAS("https://t1133727.us-p1.analyticscloud.sas.com", <port>, "<username>", "<password>")

Do you happen to know if:
1. It's possible to connect from within JupyterLab to CAS on a SAC image? 
2. If it's possible to connect via a URL rather than server address?

**Comment by nadolsw** [comment]
Doug has provided a solution which resolved the issue - many thanks!

From the JupyterLab instance inside AC, you can create a CAS session by specifying the default port 5570. The CAS server is available at localhost and authentication is handled by the /jupyter/.authinfo file. An example looks like this:

import swat
sess = swat.CAS(port=5570)
sess.builtins.about()
