### ISSUE TITLE
Changing swat.options.cas.print_messages Alters Message Indexing

### ISSUE THREAD

**Issue by DevPhelps** [sassoftware/python-swat#50]
It seems that depending on whether or not print_messages is true or not, the actual message stored in the results object changes!  I am running an action where if print_messages is TRUE, I get the following message:
ERROR: Cannot convert parameter 'nextStateNames[0]' from int64 to string.

If I change print_messages to FALSE I get:
ERROR: Cannot convert parameter 'nextStateNames[1]' from int64 to string.

I have seen this happen with other error messages as well.  Does anyone else see this behavior?  In order to see the message when you have print_messages set to FALSE, you must manually print the results.messages.

**Comment by kesmit13** [comment]
This hasn't been reported before, but it is a bug.  Since CAS uses one-indexed lists and Python uses zero-indexed lists, the client tries to patch parameter messages to match the proper index value.  However, this happens in the code that prints the messages, not the code that surfaces the messages to the Python objects.  The remapping should be done in a different place in the code.

**Comment by kesmit13** [comment]
The code has been updated with a fix, but unfortunately the library won't be available until the next server release of CAS in a few months.

**Comment by kesmit13** [comment]
This should be working correctly in SWAT v1.6.0.
