### ISSUE TITLE
Conda Installation on Python 3.8 Aborts

### ISSUE THREAD

**Issue by smlindauer** [sassoftware/python-swat#95]
When I run `conda install -c sas-institute swat` from a new Python 3.8 anaconda environment, the following message is returned and the installation stops:

> UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:
>
>Specifications:
>
 > - swat -> python[version='>=2.7,<2.8.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0|>=3.4,<3.5.0a0']
>
>Your python: python=3.8
>
>If python is on the left-most side of the chain, that's the version you've asked for.
>When python appears to the right, that indicates that the thing on the left is somehow
>not available for the python version you are constrained to. Note that conda will not
>change your python version to a different minor version unless you explicitly specify
>that.
>
>The following specifications were found to be incompatible with your CUDA driver:
>
> - feature:/win-64::__cuda==10.2=0
>
> Your installed CUDA driver is: 10.2

Running `pip install swat` successfully installs swat and I have confirmed that swat is importable in Python after the pip installation.

**Comment by kesmit13** [comment]
We haven't done a release of SWAT for Python 3.8 because of an internal release issue with the C extension that is needed.  It requires components shared with the server and those haven't been released yet.  It would be possible to create a conda package, but it would not include the C extension; it would only support the REST protocol.  That is what you are getting with the pip install now.  I don't have a known date for the release yet, but hoping it will be in the next couple of months.

**Comment by smlindauer** [comment]
Thanks for the update and quick response!

**Comment by kesmit13** [comment]
Hopefully this will be the last time this happens.  The server (and associated components) are moving to a much faster release cadence than we have had in the past.

**Comment by kesmit13** [comment]
SWAT v1.7.0 is now available with support for Python 3.8.
