### ISSUE TITLE
Support doubles in CASColumn DateTime Properties using the format to indicate data type

### ISSUE THREAD

**Issue by yjching** [sassoftware/python-swat#96]
Hi,

I am trying to use the CASColumn DateTime properties:
https://developer.sas.com/apis/swat/python/v1.4.0/api.html#datetime-properties

When I invoke these actions, I receive the following message:
![image](https://user-images.githubusercontent.com/28501550/90206982-7323b700-de28-11ea-9e8b-66980133e9ac.png)

But looking at the supported data types for CAS actions, I can see that date/times/datetimes variables are not supported
https://go.documentation.sas.com/?docsetId=pgmdiff&docsetTarget=n0b6wc0bp6tt31n1l98k9g2l2l9b.htm&docsetVersion=3.5&locale=en#n1mw56qf491ghzn1ecderjte8xyn

Is that correct? Or is there a way to convert my column into date/time/datetime to use these properties? For reference, my data is currently encoded as 'double' with an applied date format:
![image](https://user-images.githubusercontent.com/28501550/90207199-fcd38480-de28-11ea-864a-9b993fef5e74.png)

**Comment by kesmit13** [comment]
This is a bit of an oddity in the API at the moment.  The client is capable of working with CAS columns containing date, time, and datetime data, but no actions at the moment officially support those types.  Part of the problem with supporting doubles is that there isn't enough information to know how to interpret the data (is it stored as a date or a time / datetime?).  It may be possible to use the column format to indicate the type of the data, then the CASColumn column methods could act accordingly.  There are already two options in the SWAT config that indicate which formats correspond to which date / time / datetime data types (cas.dataset.date_formats & cas.dataset.datetime_formats).  If a double column didn't have a format on it, SWAT would still have to error out since it wouldn't know how to handle the data.

I'm going to reword the title of this issue to reflect this new implementation idea.

**Comment by kesmit13** [comment]
After more investigation, this shouldn't be terribly difficult to implement.  The computed columns used by the datetime methods on the CASColumn object use functions work on both CAS date / time / datetime columns as well as double columns.  The main thing that needs to be implemented is determining the type of the double value (date or datetime) based on the format to make sure the functions get called correctly.

**Comment by yjching** [comment]
Thanks for your response! I was doing some more testing of the behaviour on the side and had another question on something I observed. Specifically, if I iterate through the values of my datetime column I can use these datetime functions:

![image](https://user-images.githubusercontent.com/28501550/90468632-476f3c80-e15a-11ea-89b2-527530bd5b5d.png)

Why is this specific property behaving like this (vs. e.g. the str methods for CASColumns which can be invoked directly on the CASColumn object)?

**Comment by kesmit13** [comment]
In this case, you are actually fetching the data.  When data is fetched and there is a date / time / datetime format on the column, the value is converted to the appropriate Python data type.

**Comment by blobLead** [comment]
Hi! I would just like to know how you should query the CASTable using the .query() method when it comes to date?

I parameterized the start and end dates for the range that I want to isolate. I have data from 2019-01-01 to 2020-12-31. I only want to look at the data from 2019-03-01 to 2020-03-01 for a year worth of data.

**Comment by kesmit13** [comment]
You should be able to use date filtering syntax like in SAS expressions.
```
filtered_tbl = tbl.query("'2019-03-01'd <= DATE_COLUMN <= '2020-03-01'd")
```
